version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: starwars_postgres
    restart: always
    environment:
      POSTGRES_DB: StarWarsRPG
      POSTGRES_USER: republica
      POSTGRES_PASSWORD: orden66
    ports:
      - "5432:5432"
    volumes:
      - sw_postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  sw_postgres_data:
